### ISSUE TITLE
Current status of this proposal

### ISSUE THREAD

**Issue by barsdeveloper** [jridgewell/proposal-regexp-atomic-and-possessive#3]
I see this proposal has been withdrawn, why is it so?

**Comment by ljharb** [comment]
I don’t believe it’s ever been presented.

**Comment by jridgewell** [comment]
Hi @barsdeveloper,

I discussed this proposal with all of the regex engines, and they advised me to wait because some were actively investigating linear-time implementations that wouldn't require atomics. This didn't pan out in the end, but the proposal is now being worked on at https://github.com/tc39/proposal-regexp-atomic-operators

**Comment by barsdeveloper** [comment]
Thank you very much for the update
